apiVersion: v1
kind: Service
metadata:
  name: my-service10
spec:
  type: NodePort
  selector:
    app: my-app10
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # Container port
      nodePort: 30089 # Exposed node port (Optional, auto-assigned if not specified)

